### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ghost** [Patrick22414/sroie-dev#1]
@patrick22414

**Comment by patrick22414** [comment]
@deepseek Sorry, I should have archived this repo. This is an preliminary attempt on Task 1&2 of SROIE and has suboptimal result and it's unlikely that I will add any new stuff to this repo.

I saw you have already found my teammate's repo [ICDAR-2019-SROIE](https://github.com/zzzDavid/ICDAR-2019-SROIE) @zzzDavid. That is our final method for Task1&2, and yields better results. Please check that out.
